services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy-local
    restart: unless-stopped
    command:
      - serve
    environment:
      - TZ=IST
    user: 1000:1000
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - 80:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    networks:
      - ntfy

  wg-easy:
    container_name: tunnel
    image: ghcr.io/wg-easy/wg-easy
    restart: unless-stopped
    environment:
      - PASSWORD_HASH=${PASS}
      - WG_HOST=${IP}
    volumes:
      - ./config:/etc/wireguard
      - /lib/modules:/lib/modules
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    env_file:
      - .env
    networks:
      - ntfy

networks:
  ntfy:
    driver: bridge
