services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy-local
    restart: unless-stopped
    command:
      - serve
    environment:
      - TZ=IST
    user: 1000:1000
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /etc/ntfy:/etc/ntfy
    ports:
      - 80:80
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    networks:
      - ntfy

networks:
  ntfy:
    driver: bridge
